version: "3.8"
services:
    web_front:
        image: maalsi-tube-web-front
        build:
            context: ./
            args:
                - VITE_CLERK_PUBLISHABLE_KEY=pk_test_c3RlYWR5LWhpcHBvLTM5LmNsZXJrLmFjY291bnRzLmRldiQ
                - VITE_BASE_API_URL=http://localhost:3000
        ports:
            - "80:80"
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
        depends_on:
            - video_api
    video_api:
        image: maalsi-tube-video-api
        build: ./video_api
        ports:
            - "3000:3000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
