# Étape 1 : construction
FROM node:18-alpine AS build
WORKDIR /app
COPY package.json .
RUN npm install

COPY . .

ARG VITE_CLERK_PUBLISHABLE_KEY
ARG VITE_BASE_API_URL
ARG VITE_S3_BUCKET_KEY_ID
ARG VITE_S3_BUCKET_SECRET_ACCESS_KEY
ARG VITE_S3_BUCKET_REGION
ARG VITE_S3_BUCKET
ARG VITE_S3_BUCKET_ENDPOINT

ENV VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY
ENV VITE_BASE_API_URL=$VITE_BASE_API_URL
ENV VITE_S3_BUCKET_KEY_ID=$VITE_S3_BUCKET_KEY_ID
ENV VITE_S3_BUCKET_SECRET_ACCESS_KEY=$VITE_S3_BUCKET_SECRET_ACCESS_KEY
ENV VITE_S3_BUCKET_REGION=$VITE_S3_BUCKET_REGION
ENV VITE_S3_BUCKET=$VITE_S3_BUCKET
ENV VITE_S3_BUCKET_ENDPOINT=$VITE_S3_BUCKET_ENDPOINT


RUN npm run build

# Étape 2 : exécution
FROM caddy:latest
COPY --from=build /app/dist /usr/share/caddy
CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]

